### ISSUE TITLE
Create fails if port 443 is not exposed

### ISSUE THREAD

**Issue by jakobbraun** [exasol/terraform-aws-exasol#22]
If the security group does not expose port 443, the creation fails, since `exasol_xmlrpc.py` can't connect to the database.

For security reasons I only want to export the SSH port. All other access to the database is done via SSH tunnels.

## Dependencies

- [ ] https://github.com/exasol/cloudformation-aws-exasol/issues/2

**Comment by jakobbraun** [comment]
Depends on https://github.com/exasol/cloudformation-aws-exasol/issues/2

**Comment by ckunki** [comment]
Current ticket is blocked https://github.com/exasol/cloudformation-aws-exasol/issues/2
while the repo `cloudformation-aws-exasol` is currently archived, i.e. maybe no one is working on it.

Options: 
* O1) Identify an appropriate blocking reason, set the project attributes accordingly and maybe lower the frequency of reviewing the current ticket.
* O2) close the current ticket as "won't fix"

**Comment by ckunki** [comment]
Closing current ticket as "won't fix".
