### ISSUE TITLE
Deployment fails when setting public ip to false

### ISSUE THREAD

**Issue by morazow** [exasol/terraform-aws-exasol#7]
Currently, when user set the public_ip variable to `false` the deployment fails since the output value tries to obtain the publicIP attribute from the management node.

**Comment by karthiksadhasivam** [comment]
@morazow Looks like readme hasnt been updated to reflect the use of public_ip to true/false. does it needs to get updated?

**Comment by morazow** [comment]
Hey @karthiksadhasivam,

Thanks for pointing it out!

You are right, indeed readme does not mention `public_ip` variable. Please feel free to send a pull request for it.

Otherwise, I plan to update it next week most probably.
